[package]
name = "multiworld-admin-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
async-proto = "=0.16.9" # rocket-ws is still on tungstenite 0.19
futures = "0.3"
itertools = "0.11"
serde_json = "1"
thiserror = "1"
url = "2"

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.crossterm]
version = "0.26"
features = ["event-stream"]

[dependencies.multiworld]
path = "../multiworld"

[dependencies.ootr-utils]
git = "https://github.com/midoshouse/rust-ootr-utils"
branch = "main"

[dependencies.syn]
version = "2"
features = ["full"]

[dependencies.tokio]
version = "1"
features = ["time"]

[dependencies.tokio-tungstenite]
version = "0.19" # rocket-ws is still on tungstenite 0.19
features = ["rustls-tls-webpki-roots"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
