[package]
name = "multiworld-admin-cli"
version = "5.1.1"
edition = "2021"

[dependencies]
async-proto = "0.15.1"
futures = "0.3"
itertools = "0.10"
serde_json = "1"
thiserror = "1"

[dependencies.clap]
version = "3"
features = ["derive"]

[dependencies.crossterm]
version = "0.25"
features = ["event-stream"]

[dependencies.multiworld]
path = "../multiworld"

[dependencies.syn]
version = "1"
features = ["full"]

[dependencies.tokio]
version = "1"
features = ["net", "time"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
