[package]
name = "multiworld-admin-cli"
version = "4.0.5"
edition = "2021"

[dependencies]
async-proto = "0.15.1"
itertools = "0.10"
thiserror = "1"

[dependencies.clap]
version = "3"
features = ["derive"]

[dependencies.multiworld]
path = "../multiworld"

[dependencies.tokio]
version = "1"
features = ["net", "time"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
