[package]
name = "multiworld-admin-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
async-proto = "0.19"
futures = "0.3"
itertools = "0.12"
serde_json = "1"
thiserror = "1"
url = "2"

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["alloc", "clock"]

[dependencies.crossterm]
version = "0.27"
features = ["event-stream"]

[dependencies.multiworld]
path = "../multiworld"

[dependencies.ootr-utils]
git = "https://github.com/midoshouse/rust-ootr-utils"
branch = "main"

[dependencies.syn]
version = "2"
features = ["full"]

[dependencies.tokio]
version = "1"
features = ["parking_lot", "time"]

[dependencies.tokio-tungstenite]
version = "0.20"
features = ["rustls-tls-webpki-roots"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
