[package]
name = "multiworld-release"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = "0.1"
crossterm = "0.27"
futures = "0.3"
graphql_client = "0.13"
itertools = "0.12"
semver = "1"
tempfile = "3"
thiserror = "1"
zip = "0.6"

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.dir-lock]
git = "https://github.com/fenhl/rust-dir-lock"
branch = "main"

[dependencies.gres]
git = "https://github.com/fenhl/gres"
branch = "main"

[dependencies.log-lock]
git = "https://github.com/fenhl/log-lock"
branch = "main"

[dependencies.multiworld]
path = "../multiworld"

[dependencies.multiworld-bizhawk]
path = "../multiworld-bizhawk"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["parking_lot", "process", "sync"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
