[package]
name = "ootrmwd"
version = "2.0.1"
edition = "2021"

[dependencies]
async-proto = "0.15"
chrono = "0.4"
futures = "0.3"
thiserror = "1"
tokio-stream = "0.1"

[dependencies.clap]
version = "3"
features = ["derive"]

[dependencies.ctrlflow]
git = "https://github.com/fenhl/ctrlflow"
branch = "main"

[dependencies.multiworld]
path = "../multiworld"
features = ["sqlx"]

[dependencies.sqlx]
version = "0.6"
default-features = false
features = ["postgres", "runtime-tokio-rustls"]

[dependencies.tokio]
version = "1"
features = ["macros", "net", "rt-multi-thread", "sync"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
