[package]
name = "ootrmwd"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
async-proto = "0.16"
chrono = "0.4"
derivative = "2"
futures = "0.3"
#rocket = "0.5.0-rc.3"
thiserror = "1"

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.multiworld]
path = "../multiworld"
features = ["pyo3", "sqlx", "tokio-tungstenite"]

[dependencies.multiworld-derive]
path = "../multiworld-derive"

[dependencies.ring]
version = "0.16"
features = ["std"]

[dependencies.rocket] # required for WebSocket support
git = "https://github.com/SergioBenitez/Rocket"
branch = "master"

[dependencies.rocket-util]
git = "https://github.com/fenhl/rocket-util"
branch = "rocket-master"

[dependencies.rocket_ws]
git = "https://github.com/SergioBenitez/Rocket"
branch = "master"

[dependencies.sqlx]
version = "0.6"
default-features = false
features = ["chrono", "postgres", "runtime-tokio-rustls"]

[dependencies.tokio]
version = "1"
features = ["macros", "net", "rt-multi-thread", "sync", "time"]

[dependencies.tungstenite]
version = "0.18"
default-features = false

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
features = ["rocket-master"]
