[package]
name = "ootrmwd"
version = "5.2.0"
edition = "2021"

[dependencies]
async-proto = "0.15.1"
chrono = "0.4"
futures = "0.3"
thiserror = "1"

[dependencies.clap]
version = "3"
features = ["derive"]

[dependencies.multiworld]
path = "../multiworld"
features = ["pyo3", "sqlx", "tokio-tungstenite"]

[dependencies.sqlx]
version = "0.6"
default-features = false
features = ["postgres", "runtime-tokio-rustls"]

[dependencies.tokio]
version = "1"
features = ["macros", "net", "rt-multi-thread", "sync", "time"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
