[package]
name = "multiworld-derive"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
itertools = "0.10"
lazy-regex = "2"
proc-macro2 = "1"
quote = "1"

[dependencies.syn]
version = "2"
features = ["extra-traits"]
