[package]
name = "multiworld-updater"
version = "1.0.0"
edition = "2021"

[dependencies]
futures = "0.3"
iced_native = "0.5"
itertools = "0.10"
open = "3"
thiserror = "1"

[dependencies.clap]
version = "3"
features = ["derive"]

[dependencies.iced]
version = "0.4"
features = ["default_system_font", "pure", "tokio"]

[dependencies.multiworld]
path = "../multiworld"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "stream", "trust-dns"]

[dependencies.tokio]
version = "1"
features = ["fs", "time"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
