[package]
name = "multiworld-updater"
version = "3.0.0"
edition = "2021"

[build-dependencies]
winres = "0.1"

[dependencies]
async_zip = "0.0.7" # 0.0.8 errors when trying to unzip BizHawk
bytes = "1"
futures = "0.3"
iced_native = "0.5"
itertools = "0.10"
open = "3"
semver = "1"
thiserror = "1"
winapi = "0.3"

[dependencies.clap]
version = "3"
features = ["derive"]

[dependencies.heim]
git = "https://github.com/heim-rs/heim" # https://github.com/heim-rs/heim/issues/322
default-features = false
features = ["process"]

[dependencies.iced]
version = "0.4"
features = ["default_system_font", "pure", "tokio"]

[dependencies.image]
version = "0.24"
default-features = false
features = ["ico"]

[dependencies.multiworld]
path = "../multiworld"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "stream", "trust-dns"]

[dependencies.tokio]
version = "1"
features = ["fs", "time"]

[dependencies.tokio-util]
version = "0.7"
features = ["io"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
