[package]
name = "multiworld-updater"
version.workspace = true
authors.workspace = true
edition.workspace = true

[build-dependencies]
winres = "0.1"

[dependencies]
bytes = "1"
dark-light = "1"
futures = "0.3"
iced_native = "0.8"
itertools = "0.10"
open = "3"
#runas = "0.2" # https://github.com/mitsuhiko/rust-runas/pull/7 https://github.com/midoshouse/ootr-multiworld/security/dependabot/1
semver = "1"
sysinfo = "0.27"
tempfile = "3"
thiserror = "1"
url = "2"
winapi = "0.3"

[dependencies.async_zip]
version = "0.0.11"
features = ["full"]

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.iced]
version = "0.7"
features = ["default_system_font", "tokio"]

[dependencies.image]
version = "0.24"
default-features = false
features = ["ico"]

[dependencies.multiworld]
path = "../multiworld"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "stream"]

[dependencies.runas]
git = "https://github.com/lucasfernog/rust-runas"
branch = "chore/update-which-dep"

[dependencies.serenity]
version = "0.11"
default-features = false
features = ["utils"]

[dependencies.tokio]
version = "1"
features = ["fs", "time"]

[dependencies.tokio-util]
version = "0.7"
features = ["io"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
