[workspace]
members = ["crate/*"]
default-members = ["crate/ootrmwd"]
resolver = "2"

[workspace.package]
version = "8.0.1"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2021"

[profile.release]
lto = true
strip = true
