[package]
name = "multiworld-gui"
version.workspace = true
authors.workspace = true
edition.workspace = true

[build-dependencies]
winres = "0.1"

[dependencies]
async-proto = "0.16"
dark-light = "1"
futures = "0.3"
iced_futures = "0.6"
iced_native = "0.10"
itertools = "0.10"
oauth2 = "4"
once_cell = "1"
open = "4"
rfd = "0.11"
semver = "1"
serde_json = "1"
sysinfo = "0.29"
thiserror = "1"
tokio-stream = "0.1"
url = "2"

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["clock", "std"]

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.iced]
version = "0.9"
features = ["default_system_font", "glow", "image", "tokio"]

[dependencies.image]
version = "0.24"
default-features = false
features = ["ico"]

[dependencies.multiworld]
path = "../multiworld"

[dependencies.ootr-utils]
git = "https://github.com/midoshouse/rust-ootr-utils"
branch = "main"

[dependencies.oottracker]
git = "https://github.com/fenhl/oottracker"
branch = "main"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json", "rustls-tls", "stream"]

[dependencies.rocket]
version = "0.5.0-rc.3"
default-features = false

[dependencies.rocket-util]
git = "https://github.com/fenhl/rocket-util"
branch = "main"

[dependencies.serenity]
version = "0.11"
default-features = false
features = ["utils"]

[dependencies.tokio]
version = "1"
features = ["fs", "net", "sync", "time"]

[dependencies.tokio-tungstenite]
version = "0.19"
features = ["rustls-tls-webpki-roots"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
features = ["reqwest"]

[target.'cfg(unix)'.dependencies]
xdg = "2"

[target.'cfg(windows)'.dependencies]
directories = "5"
