[package]
name = "multiworld-gui"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = ["wgpu"]
glow = ["iced/glow"]
wgpu = ["iced_graphics"]

[build-dependencies]
winres = "0.1"

[dependencies]
async-proto = "0.16"
chrono = "0.4"
dark-light = "1"
directories = "5"
futures = "0.3"
iced_futures = "0.6"
iced_native = "0.9"
itertools = "0.10"
once_cell = "1"
open = "4"
rfd = "0.11"
semver = "1"
serde_json = "1"
sysinfo = "0.28"
thiserror = "1"
url = "2"

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.iced]
version = "0.8"
features = ["default_system_font", "image", "tokio"]

[dependencies.iced_graphics]
version = "0.7"
optional = true

[dependencies.image]
version = "0.24"
default-features = false
features = ["ico"]

[dependencies.multiworld]
path = "../multiworld"

[dependencies.ootr-utils]
git = "https://github.com/midoshouse/rust-ootr-utils"
branch = "main"

[dependencies.oottracker]
git = "https://github.com/fenhl/oottracker"
branch = "main"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json", "rustls-tls", "stream"]

[dependencies.serenity]
version = "0.11"
default-features = false
features = ["utils"]

[dependencies.tokio]
version = "1"
features = ["fs", "net", "sync", "time"]

[dependencies.tokio-tungstenite]
version = "0.18"
features = ["rustls-tls-webpki-roots"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
features = ["reqwest"]
