[package]
name = "multiworld"
version = "1.0.0"
edition = "2021"

[dependencies]
async-proto = "0.15"
async-recursion = "1"
chrono = "0.4"
itertools = "0.10"
semver = "1"
thiserror = "1"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["net", "sync"]

[dependencies.url]
version = "2"
features = ["serde"]
