[package]
name = "multiworld"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
pyo3 = ["dep:pyo3", "ootr-utils/pyo3"]

[dependencies]
async-recursion = "1"
async-trait = "0.1"
directories = "5"
futures = "0.3"
itertools = "0.10"
once_cell = "1"
ring = "0.16"
semver = "1"
serde_json = "1"
thiserror = "1"

[dependencies.async-proto]
version = "0.16"
features = ["semver"]

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["clock", "std"]

[dependencies.ootr-utils]
git = "https://github.com/midoshouse/rust-ootr-utils"
branch = "main"

[dependencies.oottracker]
git = "https://github.com/fenhl/oottracker"
branch = "main"

[dependencies.pyo3]
version = "0.18"
features = ["auto-initialize"]
optional = true

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["blocking", "json"]

[dependencies.rocket_ws]
git = "https://github.com/SergioBenitez/Rocket"
branch = "master"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.sqlx]
version = "0.6"
default-features = false
features = ["macros", "postgres"]
optional = true

[dependencies.tokio]
version = "1"
features = ["net", "process", "sync", "time"]

[dependencies.tokio-tungstenite]
version = "0.18"
features = ["rustls-tls-webpki-roots"]
optional = true

[dependencies.url]
version = "2"
features = ["serde"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
features = ["async-proto"]
