[package]
name = "multiworld"
version = "5.1.0"
edition = "2021"

[features]
style = ["dark-light", "iced"]

[dependencies]
async-proto = "0.15.1"
async-recursion = "1"
chrono = "0.4"
directories = "4"
itertools = "0.10"
lazy-regex = "2"
once_cell = "1"
semver = "1"
serde_json = "1"
thiserror = "1"

[dependencies.dark-light]
version = "0.2"
optional = true

[dependencies.iced]
version = "0.4"
features = ["pure"]
optional = true

[dependencies.oottracker]
git = "https://github.com/fenhl/oottracker"
branch = "main"

[dependencies.pyo3]
version = "0.17"
features = ["auto-initialize"]
optional = true

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["blocking", "json"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.sqlx]
version = "0.6"
default-features = false
features = ["macros", "postgres"]
optional = true

[dependencies.tokio]
version = "1"
features = ["net", "sync", "time"]

[dependencies.tokio-tungstenite]
version = "0.17"
features = ["rustls-tls-webpki-roots"]
optional = true

[dependencies.url]
version = "2"
features = ["serde"]
