[package]
name = "multiworld-bizhawk"
version.workspace = true
authors.workspace = true
edition.workspace = true

[build-dependencies]
lazy-regex = "2"
thiserror = "1"

[dependencies]
semver = "1"

[dependencies.winver]
git = "https://github.com/fenhl/winver"
branch = "main"
