[package]
name = "multiworld-bizhawk"
version.workspace = true
authors.workspace = true
edition.workspace = true

[build-dependencies]
lazy-regex = "2"
thiserror = "1"

[build-dependencies.tokio]
version = "1"
features = ["process"]

[build-dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"

[dependencies]
semver = "1"

[target.'cfg(windows)'.dependencies.winver]
git = "https://github.com/fenhl/winver"
branch = "main"
