[package]
name = "multiworld-bizhawk"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
semver = "1"

[dependencies.winver]
git = "https://github.com/fenhl/winver"
branch = "main"
