[package]
name = "multiworld-installer"
version.workspace = true
authors.workspace = true
edition.workspace = true

[build-dependencies]
thiserror = "1"
winres = "0.1"

[build-dependencies.multiworld-bizhawk]
path = "../multiworld-bizhawk"

[dependencies]
dark-light = "1"
directories = "5"
futures = "0.3"
iced_native = "0.9"
is_elevated = "0.1"
itertools = "0.10"
kuchiki = "0.8"
lazy-regex = "2"
open = "4"
rfd = "0.11"
runas = "1"
semver = "1"
serde_ini = "0.2"
tempfile = "3"
thiserror = "1"

[dependencies.async_zip]
version = "0.0.13"
features = ["full"]

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.iced]
version = "0.8"
features = ["default_system_font", "image", "tokio"]

[dependencies.image]
version = "0.24"
default-features = false
features = ["ico"]

[dependencies.multiworld]
path = "../multiworld"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json", "rustls-tls", "stream"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serenity]
version = "0.11"
default-features = false
features = ["utils"]

[dependencies.tokio]
version = "1"
features = ["fs", "process", "rt-multi-thread"]

[dependencies.tokio-util]
version = "0.7"
features = ["io"]

[dependencies.url]
version = "2"
features = ["serde"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"

[dependencies.winver]
git = "https://github.com/fenhl/winver"
branch = "main"
