[package]
name = "multiworld-installer"
version = "4.0.2"
edition = "2021"

[build-dependencies]
winres = "0.1"

[dependencies]
async_zip = "0.0.7" # 0.0.8 errors when trying to unzip BizHawk
dark-light = "0.2"
directories = "4"
futures = "0.3"
iced_native = "0.5"
is_elevated = "0.1"
itertools = "0.10"
kuchiki = "0.8"
lazy-regex = "2"
rfd = "0.9"
runas = "0.2"
serde_ini = "0.2"
tempfile = "3"
thiserror = "1"

[dependencies.clap]
version = "3"
features = ["derive"]

[dependencies.iced]
version = "0.4"
features = ["default_system_font", "image", "pure", "tokio"]

[dependencies.image]
version = "0.24"
default-features = false
features = ["ico"]

[dependencies.multiworld]
path = "../multiworld"
features = ["style"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json", "rustls-tls", "stream", "trust-dns"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["fs", "process", "rt-multi-thread"]

[dependencies.tokio-util]
version = "0.7"
features = ["io"]

[dependencies.url]
version = "2"
features = ["serde"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
