[package]
name = "multiworld-installer"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lints]
workspace = true

[build-dependencies]
thiserror = "1"
winres = "0.1"

[build-dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
features = ["reqwest"]

[target.'cfg(windows)'.build-dependencies.multiworld-bizhawk]
path = "../multiworld-bizhawk"

[target.'cfg(unix)'.build-dependencies]
itertools = "0.12"

[target.'cfg(unix)'.build-dependencies.multiworld]
path = "../multiworld"

[target.'cfg(unix)'.build-dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls"]

[dependencies]
dark-light = "1"
directories = "5"
enum-iterator = "1"
futures = "0.3"
iced_runtime = "0.1"
itertools = "0.12"
lazy-regex = "3"
open = "5"
rfd = "0.13"
semver = "1"
serde_ini = "0.2"
thiserror = "1"

[dependencies.async_zip]
version = "0.0.16"
features = ["full"]

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.iced]
version = "0.10"
default-features = false
features = ["image", "tokio"]

[dependencies.image]
version = "0.24"
default-features = false
features = ["ico"]

[dependencies.multiworld]
path = "../multiworld"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json", "rustls-tls", "stream"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serenity]
version = "0.12"
default-features = false
features = ["utils"]

[dependencies.tokio]
version = "1"
features = ["fs", "parking_lot", "process", "rt-multi-thread"]

[dependencies.url]
version = "2"
features = ["serde"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"

[target.'cfg(target_os = "linux")'.dependencies]
gio = "0.18"
tokio-tar = "0.3"
which = "6"
xdg = "2"

[target.'cfg(target_os = "linux")'.dependencies.async-compression]
version = "0.4"
features = ["gzip", "tokio"]

[target.'cfg(target_os = "windows")'.dependencies]
is_elevated = "0.1"
kuchiki = "0.8"
mslnk = "0.1"
runas = "=1.0.0" # https://github.com/mitsuhiko/rust-runas/issues/13
tempfile = "3"

[target.'cfg(target_os = "windows")'.dependencies.tokio-util]
version = "0.7"
features = ["io"]

[target.'cfg(target_os = "windows")'.dependencies.winver]
git = "https://github.com/fenhl/winver"
branch = "main"
