[package]
name = "multiworld-csharp"
version = "4.0.4"
edition = "2021"

[lib]
name = "multiworld"
crate-type = ["cdylib"]

[dependencies]
async-proto = "0.15.1"
chrono = "0.4"
directories = "4"
libc = "0.2"
semver = "1"

[dependencies.multiworld]
path = "../multiworld"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["blocking", "rustls-tls"]

[dependencies.winver]
git = "https://github.com/fenhl/winver"
branch = "main"
