[package]
name = "multiworld-csharp"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "multiworld"
crate-type = ["cdylib"]

[dependencies]
directories = "4"
libc = "0.2"
once_cell = "1"
thiserror = "1"

[dependencies.iced]
#version = "0.8"
git = "https://github.com/fenhl/iced"
branch = "any-thread"
features = ["image"]

[dependencies.image]
version = "0.24"
default-features = false
features = ["ico"]

[dependencies.multiworld]
path = "../multiworld"

[dependencies.multiworld-derive]
path = "../multiworld-derive"

[dependencies.multiworld-gui]
path = "../multiworld-gui"

[dependencies.ootr-utils]
git = "https://github.com/midoshouse/rust-ootr-utils"
branch = "main"

[dependencies.oottracker]
git = "https://github.com/fenhl/oottracker"
branch = "main"

[dependencies.tokio]
version = "1"
features = ["sync"]
