[package]
name = "multiworld-csharp"
version = "5.0.0"
edition = "2021"

[lib]
name = "multiworld"
crate-type = ["cdylib"]

[dependencies]
async-proto = "0.15.1"
directories = "4"
libc = "0.2"
once_cell = "1"
semver = "1"

[dependencies.multiworld]
path = "../multiworld"

[dependencies.multiworld-derive]
path = "../multiworld-derive"

[dependencies.oottracker]
git = "https://github.com/fenhl/oottracker"
branch = "main"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["blocking", "rustls-tls"]

[dependencies.winver]
git = "https://github.com/fenhl/winver"
branch = "main"
